stages:
  split_data:
    cmd: python src/features/split_data.py
    deps:
    - data/raw/accepted_2007_to_2018Q4.csv
    - src/features/split_data.py
    outs:
    - data/interim/train_raw.csv
    - data/interim/test_raw.csv
  clean_data:
    cmd: python src/features/clean_data.py
    deps:
    - data/interim/train_raw.csv
    - data/interim/test_raw.csv
    - src/features/clean_data.py
    outs:
    - data/interim/train_clean.csv
    - data/interim/test_clean.csv
  encode_features:
    cmd: python src/features/encode_features.py
    deps:
    - data/interim/train_clean.csv
    - data/interim/test_clean.csv
    - src/features/encode_features.py
    outs:
    - models/columns_encoder.pkl
    - data/processed/X_train.npy
    - data/processed/y_train.npy
    - data/processed/X_test.npy
    - data/processed/y_test.npy
    
  train:
    foreach:
      log_reg_full:
        name: log_reg_full
        random_state: ${train.log_reg_full.random_state}
      log_reg_rf_select:
        name: log_reg_rf_select
        random_state: ${train.log_reg_rf_select.random_state}
      xgboost:
        name: xgboost
        random_state: ${train.xgboost.random_state}
      decision_tree:
        name: decision_tree
        random_state: ${train.decision_tree.random_state}
    do:
      cmd: python src/training/train_${item.name}.py --random-state=${item.random_state}
      deps:
        - data/processed/X_train.npy
        - data/processed/y_train.npy
      outs:
        - models/${item.name}/rs_${item.random_state}.pkl
        
  # train_log_reg_rf_select:
  #   cmd: python src/training/train_log_reg_rf_select.py --random-state=${train.random_state}
  #   deps:
  #   - data/processed/X_train.npy
  #   - data/processed/y_train.npy
  #   outs:
  #   - models/log_reg_rf_select/rs_${train.random_state}.pkl

  evaluate:
    foreach:
      log_reg_full:
        name: log_reg_full
        random_state: ${train.log_reg_full.random_state}
      log_reg_rf_select:
        name: log_reg_rf_select
        random_state: ${train.log_reg_rf_select.random_state}
      xgboost:
        name: xgboost
        random_state: ${train.xgboost.random_state}
      decision_tree:
        name: decision_tree
        random_state: ${train.decision_tree.random_state}
    do:
      cmd: >-
        python src/evaluation/evaluate_model.py 
        --metrics-file=./metrics/${item.name}/rs_${item.random_state}.json
        --model-file=./models/${item.name}/rs_${item.random_state}.pkl
      deps:
        - data/processed/X_test.npy
        - data/processed/y_test.npy
        - models/${item.name}/rs_${item.random_state}.pkl
      metrics:
        - ./metrics/${item.name}/rs_${item.random_state}.json
  
  # train_log_reg_full:
  #   cmd: python src/training/train_log_reg_full.py
  #   deps:
  #   - data/processed/X_train.npy
  #   - data/processed/y_train.npy
  #   outs:
  #   - models/log_reg_full.pkl
  # train_log_reg_rf_select:
  #   cmd: python src/training/train_log_reg_rf_select.py
  #   deps:
  #   - data/processed/X_train.npy
  #   - data/processed/y_train.npy
  #   outs:
  #   - models/log_reg_rf_select.pkl
  # train_xgboost:
  #   cmd: python src/training/train_xgboost.py
  #   deps:
  #   - data/processed/X_train.npy
  #   - data/processed/y_train.npy
  #   outs:
  #   - models/xgboost.pkl
  # train_decision_tree:
  #   cmd: python src/training/train_decision_tree.py
  #   deps:
  #   - data/processed/X_train.npy
  #   - data/processed/y_train.npy
  #   outs:
  #   - models/decision_tree.pkl

  # evaluate_log_reg_full:
  #   cmd: >-
  #     python src/evaluation/evaluate_model.py 
  #     --metrics-file=./metrics/log_reg_full.json
  #     --model-file=./models/log_reg_full.pkl
  #   deps:
  #   - data/processed/X_test.npy
  #   - data/processed/y_test.npy
  #   - models/log_reg_full.pkl
  #   metrics:
  #   - ./metrics/log_reg_full.json
  # evaluate_log_reg_rf_select:
  #   cmd: >-
  #     python src/evaluation/evaluate_model.py 
  #     --metrics-file=./metrics/log_reg_rf_select.json
  #     --model-file=./models/log_reg_rf_select.pkl
  #   deps:
  #   - data/processed/X_test.npy
  #   - data/processed/y_test.npy
  #   - models/log_reg_rf_select.pkl
  #   metrics:
  #   - ./metrics/log_reg_rf_select.json
  # evaluate_xgboost:
  #   cmd: >-
  #     python src/evaluation/evaluate_model.py 
  #     --metrics-file=./metrics/xgboost.json
  #     --model-file=./models/xgboost.pkl
  #   deps:
  #   - data/processed/X_test.npy
  #   - data/processed/y_test.npy
  #   - models/xgboost.pkl
  #   metrics:
  #   - ./metrics/xgboost.json
  # evaluate_decision_tree:
  #   cmd: >-
  #     python src/evaluation/evaluate_model.py 
  #     --metrics-file=./metrics/decision_tree.json
  #     --model-file=./models/decision_tree.pkl
  #   deps:
  #   - data/processed/X_test.npy
  #   - data/processed/y_test.npy
  #   - models/decision_tree.pkl
  #   metrics:
  #   - ./metrics/decision_tree.json