stages:
  split_data:
    cmd: python src/features/split_data.py
    deps:
    - data/raw/accepted_2007_to_2018Q4.csv
    - src/features/split_data.py
    outs:
    - data/interim/train.csv
    - data/interim/test.csv