stages:
  split_data:
    cmd: python src/features/split_data.py
    deps:
    - data/raw/accepted_2007_to_2018Q4.csv
    - src/features/split_data.py
    outs:
    - data/interim/train_raw.csv
    - data/interim/test_raw.csv
  clean_data:
    cmd: python src/features/clean_data.py
    deps:
    - data/interim/train_raw.csv
    - data/interim/test_raw.csv
    - src/features/clean_data.py
    outs:
    - data/interim/train_clean.csv
    - data/interim/test_clean.csv
  encode_features:
    cmd: python src/features/encode_features.py
    deps:
    - data/interim/train_clean.csv
    - data/interim/test_clean.csv
    - src/features/encode_features.py
    outs:
    - models/columns_encoder.pkl
    - data/processed/X_train.npy
    - data/processed/y_train.npy
    - data/processed/X_test.npy
    - data/processed/y_test.npy
    
  train_log_reg_full:
    cmd: python src/models/training/train_log_reg_full.py
    deps:
    - data/processed/X_train.npy
    - data/processed/y_train.npy
    outs:
    - models/log_reg_full.pkl
  train_log_reg_rf_select:
    cmd: python src/models/training/train_log_reg_rf_select.py
    deps:
    - data/processed/X_train.npy
    - data/processed/y_train.npy
    outs:
    - models/log_reg_rf_select.pkl
    - models/random_forest.pkl
  train_xgboost:
    cmd: python src/models/training/train_xgboost.py
    deps:
    - data/processed/X_train.npy
    - data/processed/y_train.npy
    outs:
    - models/xgboost.pkl
  train_decision_tree:
    cmd: python src/models/training/train_decision_tree.py
    deps:
    - data/processed/X_train.npy
    - data/processed/y_train.npy
    outs:
    - models/decision_tree.pkl
    
  # evaluate_log_reg_full:
  #   cmd: python src/models/evaluation/evaluate_model.py
  #   deps:
  #   - data/processed/X_test.npy
  #   - data/processed/y_test.npy
  #   - models/log_reg_full.pkl
  # evaluate_log_reg_rf_select:
  #   cmd: python src/models/evaluation/evaluate_model.py
  #   deps:
  #   - data/processed/X_test.npy
  #   - data/processed/y_test.npy
  #   - models/log_reg_rf_select.pkl