stages:
  train:
    foreach:
      log_reg_full:
        name: log_reg_full
        random_state: ${train.log_reg_full.random_state}
      log_reg_rf_select:
        name: log_reg_rf_select
        random_state: ${train.log_reg_rf_select.random_state}
      xgboost:
        name: xgboost
        random_state: ${train.xgboost.random_state}
      decision_tree:
        name: decision_tree
        random_state: ${train.decision_tree.random_state}
    do:
      cmd: python src/training/train_${item.name}.py --random-state=${item.random_state}
      wdir: ../../
      deps:
        - data/processed/X_train.npy
        - data/processed/y_train.npy
        - src/training/train_${item.name}.py
      outs:
        - models/${item.name}/rs_${item.random_state}.pkl

  evaluate:
    foreach:
      log_reg_full:
        name: log_reg_full
        random_state: ${train.log_reg_full.random_state}
      log_reg_rf_select:
        name: log_reg_rf_select
        random_state: ${train.log_reg_rf_select.random_state}
      xgboost:
        name: xgboost
        random_state: ${train.xgboost.random_state}
      decision_tree:
        name: decision_tree
        random_state: ${train.decision_tree.random_state}
    do:
      cmd: >-
        python src/evaluation/evaluate_model.py 
        --metrics-file=./metrics/${item.name}/rs_${item.random_state}.json
        --model-file=./models/${item.name}/rs_${item.random_state}.pkl
      wdir: ../../
      deps:
        - data/processed/X_test.npy
        - data/processed/y_test.npy
        - models/${item.name}/rs_${item.random_state}.pkl
        - src/evaluation/evaluate_model.py
      metrics:
        - ./metrics/${item.name}/rs_${item.random_state}.json